-- Borra todas las tablas del esquema actual
DROP TABLE IF EXISTS Entrada CASCADE;
DROP TABLE IF EXISTS Funcion_Especial CASCADE;
DROP TABLE IF EXISTS Funcion CASCADE;
DROP TABLE IF EXISTS Empleado CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
DROP TABLE IF EXISTS Persona CASCADE;
DROP TABLE IF EXISTS Pelicula CASCADE;
DROP TABLE IF EXISTS Sala CASCADE;